---
sources:
  - Cassandra:
      name: "cassandra"
      listen_addr: "127.0.0.1:9042"
      chain:
        - Tee:
            behavior: Ignore
            # Timeout for sending to the sub chain in microseconds
            timeout_micros: 1000
            # The number of message batches that the tee can hold onto in its buffer of messages to send.
            # If they arent sent quickly enough and the buffer is full then tee will drop new incoming messages.
            buffer_size: 10000
            # The sub chain to send duplicate messages through
            chain:
              - CassandraSinkCluster:
                  first_contact_points: ["172.16.2.2:9044", "172.16.2.3:9044"]
                  local_shotover_host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
                  shotover_nodes:
                    - address: "127.0.0.1:9042"
                      data_center: "datacenter1"
                      rack: "rack1"
                      host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
                  connect_timeout_ms: 3000
        - CassandraSinkCluster:
            first_contact_points: ["172.16.1.2:9044", "172.16.1.3:9044"]
            local_shotover_host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
            shotover_nodes:
              - address: "127.0.0.1:9042"
                data_center: "datacenter1"
                rack: "rack1"
                host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
            connect_timeout_ms: 3000
